linters:
    BorderZero:
        enabled: false
    CapitalizationInSelector:
        enabled: true
    ColorKeyword:
        enabled: true
    ColorVariable:
        enabled: false
    Comment:
        enabled: true
    DebugStatement:
        enabled: true
    DeclarationOrder:
        enabled: false
    DuplicateProperty:
        enabled: false
    ElsePlacement:
        enabled: true
    EmptyLineBetweenBlocks:
        enabled: false
    EmptyRule:
        enabled: false
    FinalNewline:
        enabled: true
    HexLength:
        enabled: true
    HexNotation:
        enabled: false
    HexValidation:
        enabled: true
    IdSelector:
        enabled: false
    IdWithExtraneousSelector:
        enabled: true
    ImportantRule:
        enabled: false
    Indentation:
        enabled: false
        width: 4
    LeadingZero:
        enabled: true
        style: include_zero
    MergeableSelector:
        enabled: false
    NameFormat:
        enabled: false
    NestingDepth:
        enabled: false
    PlaceholderInExtend:
        enabled: false
    PropertySortOrder:
        enabled: false
    PropertySpelling:
        enabled: true
    PseudoElement:
        enabled: false
    QualifyingElement:
        enabled: false
    SelectorDepth:
        enabled: false
    SelectorFormat:
        enabled: false
    Shorthand:
        enabled: false
    SingleLinePerSelector:
        enabled: false
    SpaceAfterComma:
        enabled: true
    SpaceAfterPropertyColon:
        enabled: true
    SpaceAfterPropertyName:
        enabled: true
    SpaceBeforeBrace:
        enabled: true
    SpaceBetweenParens:
        enabled: true
    StringQuotes:
        enabled: false
        style: single_quotes
    TrailingSemicolon:
        enabled: false
    TrailingSemicolonAfterPropertyValue:
        enabled: false
    UnnecessaryMantissa:
        enabled: true
    UrlFormat:
        enabled: true
    UrlQuotes:
        enabled: false
    VendorPrefix:
        enabled: false
    ZeroUnit:
        enabled: true
